apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: throwaway-hello-app
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: textninja/hello:1.0.0
