apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: throwaway-hello-app
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
